Repository Dev-JoseRonaldo/Dijkstra, pull requests merged in 2023-08, with the labels that each got.

#1 feat: add database
  database/celegansneural.gml
Labels: feat

#2 feat: read data from database
  src/read_data.py
Labels: feat

#3 feat: add dijkstra algorithm
  src/djikstra.py
  src/read_data.py
Labels: feat

#4 feat: add grafic interface and graph plot
  main.py
  src/dijkstra.py
Labels: feat

#5 fix: adjust plot shortest path graph
  main.py
Labels: fix

#7 refactor: adjust interface layout
  image/bg.png
  main.py
Labels: refactor

#8 docs: update readme
  README.md
Labels: docs
